### ISSUE TITLE
pre-configure client to accept the server's certificate?

### ISSUE THREAD

**Issue by nictuku** [scaleway-community/scaleway-camlistore#2]
Hi. I had some struggles with camlistore using this image, in part because the local client configuration (used by cammount for example) does not trust the local server's certificate. The server uses TLS, so the client can't talk to the server out of the box.

It would be nice if the client was pre-configured to accept the local server's certificate. Since it's local communication, authentication of the server shouldn't be super important.

**Comment by mpl** [comment]
@nictuku In addition to missing the correct "trustedCerts" field, the default client config created by camput init will also have incorrect values for "Server" (http instead of https), and "Auth" (localhost instead of a userpass), so I assume you had to fix those too, right? So having camput init just add the correct "trustedCerts" wouldn't be enough to give you a working config.

The client initialization process is giving a hint about the GPG keyID to use with camput init because that's the most annoying one for a user to figure out. Now you're saying "trustedCerts" is annoying too. But I don't think it makes much sense to give you a config with a correct "trustedCerts" and only (incorrect) default values for the other fields. So I'm wondering  whether we couldn't have camput init give you a fully workable config (at least when run on the same host as the server).

And now I've just remembered that https://yourcamlihost:3179/help/ pretty much gives you the correct config in that case, so I'm not sure.
It might be doable to make camput init to do all the work, but it would be so easy for it to output that URL instead that I think I'm going to start with that.

Thoughts?

**Comment by mpl** [comment]
@nictuku PTAL @ https://camlistore-review.googlesource.com/5396

I'm hoping that with this I can just add something like
  camput -server https://localhost:3179 init -userpass foo:bar -insecure=true
to the camlistore-configure program, and that should give the user a fully working client config out of the box.

**Comment by mpl** [comment]
@nictuku PTAL @ https://github.com/scaleway-community/scaleway-camlistore/pull/8

**Comment by nictuku** [comment]
Nice! Closing since it looks fixed. I'll try to make a test deployment at some point and re-open if it doesn't work. Thanks again!

**Comment by mpl** [comment]
well, unless you build the image yourself from the repo, you first have to wait for the scaleway team to update the image though.

**Comment by moul** [comment]
Here it is: https://cloud.scaleway.com/#/servers/new?image=e485269b-fe65-4e78-80fc-a7e349770b95

**Comment by moul** [comment]
Typo, I just updated the [link](https://cloud.scaleway.com/#/servers/new?image=94b9bf7e-1380-4af4-9c6a-9331a82c3dfc)

**Comment by mpl** [comment]
thanks
